import { componentTypeValues } from "astro-cms:manifest";
import { componentRegistry as projectComponentRegistry } from "astro-cms:registry";
import type { ComponentType } from "./document-types";

function componentFor(type: ComponentType): unknown {
  const component = projectComponentRegistry[type];

  if (!component) {
    throw new Error(
      `The component manifest registers ${type}, but ${type}.astro does not exist in the configured component directory.`,
    );
  }

  return component;
}

/**
 * Generated by the Astro integration from the adopting project's native
 * component directory. The manifest key/file-name convention removes a
 * second hand-maintained registry.
 */
export const componentRegistry = Object.fromEntries(
  componentTypeValues.map((type) => [type, componentFor(type)]),
) as Record<ComponentType, unknown>;
